services:
  server:
    build:
      context: ./apps/server
      dockerfile: dockerfile

    ports:
      - "8000:8000"

    environment:
      NODE_ENV: production
      PORT: 8000

      # Qdrant
      QDRANT_URL: http://qdrant:6333

      # Valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379

      # BullMQ
      BULL_MQ_HOST: valkey
      BULL_MQ_PORT: 6379

      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # LangSmith
      LANGSMITH_TRACING: ${LANGSMITH_TRACING}
      LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}

    volumes:
      - uploads:/app/uploads

    depends_on:
      - qdrant
      - valkey

    restart: unless-stopped

  worker:
    build:
      context: ./apps/server
      dockerfile: dockerfile

    command: ["node", "worker.js"]

    environment:
      NODE_ENV: production

      # Valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379

      # Qdrant
      QDRANT_URL: http://qdrant:6333

      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    volumes:
      - uploads:/app/uploads

    depends_on:
      - valkey
      - qdrant

    restart: unless-stopped

  client:
    build:
      context: ./apps/client
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}

    depends_on:
      - server

    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

    volumes:
      - qdrant_storage:/qdrant/storage

    restart: unless-stopped

  valkey:
    image: valkey/valkey

    volumes:
      - valkey_data:/data

    restart: unless-stopped

volumes:
  # Uploaded PDFs
  uploads:

  # Qdrant vector database
  qdrant_storage:

  # Valkey data
  valkey_data:
