# Stage 1: Build & Dependencies
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
# Install ALL dependencies (including build tools if needed)
RUN npm install
COPY . .

# Stage 2: Production Runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8000


COPY package*.json ./
# Install ONLY production dependencies to keep the image slim
RUN npm install --force --only=production

# Copy built files from the builder stage
COPY --from=builder /app ./

EXPOSE 8000

CMD ["node", "index.js"] 